# Generated by Django 2.1.5 on 2019-02-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='weight',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='foods',
            new_name='mass',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='breed',
            new_name='type',
        ),
    ]
